[book]
author = "러스트 프로젝트 개발자들"
title = "러스토노미콘"
description = "심오하고 불안전한 러스트 프로그래밍의 흑마법들"

[output.html]
additional-css = ["theme/nomicon.css"]
git-repository-url = "https://github.com/nomicon-kr/nomicon-kr.github.io"

[output.html.redirect]
# Vec-related chapters.
"./vec-alloc.html" = "./vec/vec-alloc.html"
"./vec-dealloc.html" = "./vec/vec-dealloc.html"
"./vec-deref.html" = "./vec/vec-deref.html"
"./vec-drain.html" = "./vec/vec-drain.html"
"./vec-final.html" = "./vec/vec-final.html"
"./vec-insert-remove.html" = "./vec/vec-insert-remove.html"
"./vec-into-iter.html" = "./vec/vec-into-iter.html"
"./vec-layout.html" = "./vec/vec-layout.html"
"./vec-push-pop.html" = "./vec/vec-push-pop.html"
"./vec-raw.html" = "./vec/vec-raw.html"
"./vec-zsts.html" = "./vec/vec-zsts.html"
"./vec.html" = "./vec/vec.html"

# Arc and Mutex related chapters.
"./arc-and-mutex.html" = "./arc-mutex/arc-and-mutex.html"
"./arc-base.html" = "./arc-mutex/arc-base.html"
"./arc-clone.html" = "./arc-mutex/arc-clone.html"
"./arc-drop.html" = "./arc-mutex/arc-drop.html"
"./arc-final.html" = "./arc-mutex/arc-final.html"
"./arc-layout.html" = "./arc-mutex/arc-layout.html"
"./arc.html" = "./arc-mutex/arc.html"

[rust]
edition = "2021"
